### ISSUE TITLE
Remove `is_numeric_or_bool`

### ISSUE THREAD

**Issue by pepone** [icerpc/slicec#674]
This method is not longer used in `slicec-cs`, removed usage in https://github.com/icerpc/icerpc-csharp/commit/dc59a88e756ace6d0f854545d4200bad2ba511bd

It is only used in  https://github.com/icerpc/slicec/blob/2ff4c72098464fe6ab98af1c795617772ddc980b/src/grammar/elements/sequence.rs#L26

But seems it is redundant, as mentioned by @InsertCreativityHere  in `slicec-cs` recent review https://github.com/icerpc/icerpc-csharp/pull/3781#discussion_r1400738036

**Comment by InsertCreativityHere** [comment]
Removed in c6f4cebbf22de24e460be667715840a872d92c66.
