### ISSUE TITLE
Rename Result ok_type and err_type

### ISSUE THREAD

**Issue by bernardnormier** [icerpc/slicec#690]
These should be success_type and failure_type, as per #648.

**Comment by InsertCreativityHere** [comment]
This was fixed in be25fbee5ee266c5ff46ace728f96c9d23d914ba

These names were only used internally in the compiler(s), so no where else needs fixing.
If you're adding `Result` to `slicec-cs`, make sure to pull in the latest version of `slicec` to get these changes.
